import {Bell,Globe2,Home,PlusCircle,Search,Users,Rss,MoreHorizontal} from 'lucide-react'; import {useState} from 'react'; import {useNavigate} from 'react-router-dom';
const posts=[['Riba_X?X','“O que dá a impressão de que o objeto está se aproximado ou se afastando do observador....”'],['CentriMais','“Eu estava levando uma mesa pro meu quarto quando de repente a mesa tombou e derrubou...”'],['Blumax_XX','“O dispositivo mais moderno para a transmissão de imagens, que substitui as antigas válvulas...”'],['DanielMFR','“Mais uma atividade recente do perfil e uma nova conversa na comunidade.”']];
function Avatar({index,large=false}:{index:number;large?:boolean}){return <div className={'avatar avatar-'+index+(large?' avatar-large':'')} aria-hidden="true"/>}
export function ForumPerfil(){const navigate=useNavigate();const [active,setActive]=useState('profile');const [following,setFollowing]=useState(false);const go=(key:string,path:string)=>{setActive(key);navigate(path)};return <main className="mobile-page">
<header className="topbar"><button className="brand" aria-label="Fórum"><span>adrenaline</span></button><div className="top-actions"><button aria-label="Comunidade pública"><Globe2 size={23}/></button><button aria-label="Notificações" onClick={()=>navigate('/notificacoes')}><Bell size={23}/><i/></button><button aria-label="Meu perfil"><Avatar index={0}/></button></div></header>
<section className="cover"><div className="cover-art"/></section>
<section className="profile"><div className="profile-photo"><Avatar index={1} large/></div><div className="profile-name">DanielMFR</div>
<div className="stats">{[['Tópicos','6'],['Favoritos','19'],['Postagens','28'],['Atividades','28']].map(([label,value])=><button key={label} className="stat"><strong>{label}</strong><span>{value}</span></button>)}</div>
<div className="section-title">Postagens</div><div className="post-list">{posts.map(([author,text],index)=><article className="post" key={author+index}><Avatar index={index+2}/><div className="post-copy"><div className="post-author">{author} <span>›</span> <b>DanielMFR</b></div><p>{text}</p></div><MoreHorizontal size={17} className="post-menu"/></article>)}</div></section>
<nav className="bottom-nav" aria-label="Navegação principal"><button className={active==='home'?'active':''} onClick={()=>go('home','/forum')}><Home size={24}/></button><button className={active==='search'?'active':''} onClick={()=>go('search','/pesquisa')}><Search size={24}/></button><button className="create" aria-label="Criar"><PlusCircle size={60}/></button><button className={active==='users'?'active':''} onClick={()=>go('users','/forum')}><Users size={24}/></button><button className={active==='feed'?'active':''} onClick={()=>go('feed','/feed')}><Rss size={24}/></button></nav>
<button className={'follow-fab '+(following?'following':'')} onClick={()=>setFollowing(v=>!v)}>{following?'Seguindo':'+'}</button>
</main>}
