export const FIGMA_ASSETS = {
  // Binary Figma exports are persisted in this repository under public/figma.
  banner: '/figma/raw-01.png',
  avatar01: '/figma/raw-02.png',
  logo: '/figma/raw-03.png',
  avatar02: '/figma/raw-04.png',
  avatar03: '/figma/raw-05.png',
  avatar04: '/figma/raw-06.png',
  avatar05: '/figma/raw-07.png',
  cover: 'https://raw.githubusercontent.com/Inosuke-Company/Assets-forum/main/assets/figma/0-1/raw-08.png',
  avatar06: '/figma/raw-10.jpeg',
  avatar07: '/figma/raw-11.png',
  avatar08: '/figma/raw-12.png',
  avatar09: '/figma/raw-13.png',
  asset14: '/figma/raw-14.png',
  asset15: '/figma/raw-15.png',
  asset16: '/figma/raw-16.png',
  asset17: '/figma/raw-17.png',
  asset18: '/figma/raw-18.png',
  asset19: '/figma/raw-19.png',
  asset20: '/figma/raw-20.png',
} as const;
