export const FIGMA_ASSETS = {
  logo: 'https://raw.githubusercontent.com/Inosuke-Company/Assets-forum/main/assets/figma/0-1/raw-01.png',
  avatar01: 'https://raw.githubusercontent.com/Inosuke-Company/Assets-forum/main/assets/figma/0-1/raw-02.png',
  avatar02: 'https://raw.githubusercontent.com/Inosuke-Company/Assets-forum/main/assets/figma/0-1/raw-03.png',
  avatar03: 'https://raw.githubusercontent.com/Inosuke-Company/Assets-forum/main/assets/figma/0-1/raw-04.png',
  avatar04: 'https://raw.githubusercontent.com/Inosuke-Company/Assets-forum/main/assets/figma/0-1/raw-05.png',
  avatar05: 'https://raw.githubusercontent.com/Inosuke-Company/Assets-forum/main/assets/figma/0-1/raw-06.png',
  avatar06: 'https://raw.githubusercontent.com/Inosuke-Company/Assets-forum/main/assets/figma/0-1/raw-07.png',
  cover: 'https://raw.githubusercontent.com/Inosuke-Company/Assets-forum/main/assets/figma/0-1/raw-08.png',
  banner: 'https://raw.githubusercontent.com/Inosuke-Company/Assets-forum/main/assets/figma/0-1/raw-09.png',
  avatar07: 'https://raw.githubusercontent.com/Inosuke-Company/Assets-forum/main/assets/figma/0-1/raw-10.jpeg',
  avatar08: 'https://raw.githubusercontent.com/Inosuke-Company/Assets-forum/main/assets/figma/0-1/raw-11.png',
  avatar09: 'https://raw.githubusercontent.com/Inosuke-Company/Assets-forum/main/assets/figma/0-1/raw-12.png',
  avatar10: 'https://raw.githubusercontent.com/Inosuke-Company/Assets-forum/main/assets/figma/0-1/raw-13.png',
} as const;
